[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "dc22ceb8c960915af346598ace72c6c9cbb6574d"
os = "macos"

    [[FFTW.download]]
    sha256 = "771ea979bb4268ab1b84b783cfe21c43a50a407ad972b7ca26a68cd9768e8a5f"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.aarch64-apple-darwin.tar.gz"
[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "24176b1cad30b49f1b5d248bc6d351beb14e67d9"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "d99d81e8bbdbec5a53259fee8212ef9ab22fa2ff51db070f3d235c69b45fbcf5"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.aarch64-linux-gnu.tar.gz"
[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "3938a79f0043670dee1e4bff0a4db3bcb49f62a3"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "4daa75ad61e58a6998df1754e754ffe04e5df4bf0cc7b0312913ed5e3d09144d"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.aarch64-linux-musl.tar.gz"
[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "85ed255c61d5cbecbfe02526f2dc9ea4949ae421"
os = "freebsd"

    [[FFTW.download]]
    sha256 = "a365585776bc067b6a783fe1666f0bdecca704a957445995ba6ca6fb019e46cf"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.aarch64-unknown-freebsd.tar.gz"
[[FFTW]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b3bd5ab1e6b0d515d8b956d318718e0e8b4b5bda"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "ab786f8d20a1fae1285e3a939a4434d97fa1041bedceac467f7b2d1ab3e5b0e6"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.armv6l-linux-gnueabihf.tar.gz"
[[FFTW]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5397096332e75abfb9ad28bfe756fd4ff2f88404"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "6bac2f484a1f7d7271e8a9150b2514fd55773fe553e0d25334d2b6bc58b46c12"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.armv6l-linux-musleabihf.tar.gz"
[[FFTW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "daa5ac5939805776148495f755f4347f86c0e265"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "a2bf7bffca694e933c0f8026e34f910d40e4ee99a334775a0038d36b871abd81"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.armv7l-linux-gnueabihf.tar.gz"
[[FFTW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e14cfcac39a761ec8d08e1aaf309d3dad609938f"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "94218bcf61fea962ff871c91ae2b9d80a1a9d74e2a2b6c47ce67106926ea7173"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.armv7l-linux-musleabihf.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "e5312f55497bf2c2a72af23f9387e6a5c6823ca8"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "f801d7e3d48b2c2e91393518308bb15e430ebf30bf78c5c2538df51960cab9a5"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.i686-linux-gnu.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "1b4ebd058be01f5ba5abf56e9b66955455df5885"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "5b7dda6d6c800c21ee80a23abc39fb50c947d97339f472696106ac4e3ecbdd10"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.i686-linux-musl.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "c6e4f366e1bcf50955bdcf25cb38432c9a3f70b3"
os = "windows"

    [[FFTW.download]]
    sha256 = "211588039804c66b71ff0fcccc4b636774575911dda14303597a6f219fb30eaa"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.i686-w64-mingw32.tar.gz"
[[FFTW]]
arch = "powerpc64le"
git-tree-sha1 = "5ea36e159db7f41a12843d85272fdfb818c59110"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "660d80079ca752fe6be760240163d0022a1bff93f1192759c207a6bc4b720534"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.powerpc64le-linux-gnu.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "7cd979618f6ae50439eab63d2ce0e8d6a7ffc6e1"
os = "macos"

    [[FFTW.download]]
    sha256 = "db63b51497b9afea9a315af7cada16014106a931ad6e22bf7087c4fc10afa529"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.x86_64-apple-darwin.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "fb9c131c2482480bc4019382138c55c7efb03741"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "23f04fce4d23d1b18a002565cbee3fe344df5b371a7bb3fa5e931d1e71e2dfc5"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.x86_64-linux-gnu.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "03c97da5072932356c08d27eb415838312378044"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "7c9164a3fc492077b27fa4ff7e89ba9f9e4c66ddb2e254de17fd1ea97e21ee53"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.x86_64-linux-musl.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "58957eaa04483d8274043b382f3a35a04f7aa72c"
os = "freebsd"

    [[FFTW.download]]
    sha256 = "adade9415fcde7aa354751ae0e70d32790282c8239170bf53f83e9acb7004148"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.x86_64-unknown-freebsd.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "3c022ff2288ed435853dce56f7af55cee181df5a"
os = "windows"

    [[FFTW.download]]
    sha256 = "4aeaf4d5ce969413840bb7d5903eca5ed2bb88d1ab19989cebc3846abf405cb9"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.10+1/FFTW.v3.3.10.x86_64-w64-mingw32.tar.gz"
