[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "1ee89460a228daf4f3bedd83142e625f52c8bd2e"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "ed7fbfe6abd31ba5e47569ff1ebc6b754d7adfdbc9f27478634de495dbc54d32"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+0/FFTW.v3.3.9.x86_64-linux-gnu.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "4c124a58fc3cd7891721fc3bdb52af6f2ef8fb4e"
os = "macos"

    [[FFTW.download]]
    sha256 = "1f4f99aadb78adc4a0d7df10097a1291c478355255bdd61979b5cdd116f56dac"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+0/FFTW.v3.3.9.x86_64-apple-darwin14.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "54ad935d3ee3014f193f323f667116e3e2cce2ae"
os = "windows"

    [[FFTW.download]]
    sha256 = "644422a04bfa8c74a8cc7b3750083e645a632c80ce03f69a7cc912ee6cf91552"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+0/FFTW.v3.3.9.i686-w64-mingw32.tar.gz"
[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "2a549320d78339c42d048bb0e70954724e984a64"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "70a68ce1e89536a8ee8df427de28f527c69d31f28cd223ebf8cf7402f3b45e50"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+0/FFTW.v3.3.9.aarch64-linux-gnu.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "606f92a1de08c4fa9b573278ebeb3706685c2151"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "9f731365440b19edb8e462a59174a20c2f27df83ab55a2c1e6e4edcbb40a132d"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+0/FFTW.v3.3.9.i686-linux-musl.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "b77917304cf58dbb16676361c56dcdc62512e404"
os = "windows"

    [[FFTW.download]]
    sha256 = "6793204f0d51a99948fa7983d798c2cbfa696df6e2e5452253ad874fe47b3143"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+0/FFTW.v3.3.9.x86_64-w64-mingw32.tar.gz"
[[FFTW]]
arch = "powerpc64le"
git-tree-sha1 = "4b79ee403016197c0d40769f3306a5c2191b5cda"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "ab5f703b110f8af01796e7f31cd11082c7bb27d7184b07f5e8da939dd1b0f2fd"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+0/FFTW.v3.3.9.powerpc64le-linux-gnu.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "d04fe71982d56eb9768386922b3b90521c3272d4"
os = "freebsd"

    [[FFTW.download]]
    sha256 = "6ff38bce55886dc4d7cf875f17bbec2b2ffa5b5eb54389ef9c5d8461f4e40c82"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+0/FFTW.v3.3.9.x86_64-unknown-freebsd11.1.tar.gz"
[[FFTW]]
arch = "armv7l"
git-tree-sha1 = "da8fca01e511e38dcebee6c5c11fe54d508ad16e"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "c869cdf7bf12c4f6d4d3359a1c6f14ec59ac84dc96672495f730a30800489b9e"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+0/FFTW.v3.3.9.arm-linux-musleabihf.tar.gz"
[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "8d66ee97bf225816018f0cd447a2fe7616d79dc4"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "a51a44344e0e99ebde48b20495a2c44aeefa51b39a2160932c9cf267d14aa6cf"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+0/FFTW.v3.3.9.aarch64-linux-musl.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "76acebf2043ceb095142f1921fec94054df3025c"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "651f7d53dea2b95ae26799f352bea8bd4c17e4371c8faeb3cbb37db9d17b2a84"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+0/FFTW.v3.3.9.i686-linux-gnu.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "668ad6c9e053e558639007687daa53a76177890f"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "35babebbb69d0bdcb8865372dcbeee3f5cd690cd470be148afd4ea6cec5015c0"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+0/FFTW.v3.3.9.x86_64-linux-musl.tar.gz"
[[FFTW]]
arch = "armv7l"
git-tree-sha1 = "a4dc239e8b401f68887a4c5aeafe46e34489ec64"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "2ee40e4d2561f656366eb147213ed483bfd4d3b63ef07359a361ccda48baca94"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+0/FFTW.v3.3.9.arm-linux-gnueabihf.tar.gz"
