[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "1082735658c9681df84fd5b477792241a4b96a9a"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "1bee957ae0289eeafbbe512bfbde31c86e566ba8b24e8094656028868d41cb86"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+4/FFTW.v3.3.9.aarch64-linux-musl.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "4da693e747bc4736fc3f6579d199d73538c4037c"
os = "windows"

    [[FFTW.download]]
    sha256 = "c9838326d474e38ba69b29553bc9fecf93a9a506aa5613b2991b05db93cc7719"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+4/FFTW.v3.3.9.i686-w64-mingw32.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "f6d76e9cd153c05a0411ca7e479de044bb96c55e"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "5d083b9d9fb22496c3ac1801c7635b7e61a95bb123bf81b238acd23724f6138a"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+4/FFTW.v3.3.9.x86_64-linux-musl.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "b6f46daa75b49b70ae4933056324923c26874c00"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "7bc6b75174c981efa5c93563fbea789c16ddad325f4cf7de7f7b0f64079b7174"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+4/FFTW.v3.3.9.i686-linux-gnu.tar.gz"
[[FFTW]]
arch = "armv7l"
git-tree-sha1 = "ce80aeda787965046936e87759f9dc7397aace39"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "26fb06d42921e31d1ac2aae9c719fc0edd8eba2ba3d77150de5896902b31af4b"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+4/FFTW.v3.3.9.armv7l-linux-gnueabihf.tar.gz"
[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "0a2da7b86b899ced2419ac2eeae1bd80c18fcdfd"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "fb89a9342ae7dbc2c9499085e133ffe7ac7bb00f159f4557f5dfe01de0762520"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+4/FFTW.v3.3.9.aarch64-linux-gnu.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "1f7802d864a42a8958dafb40427722f8a7abbe07"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "96e6c40fbe167aa6a3c863c0a63cc28cf8cd52aa186b8f12464e8ed7be7beb73"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+4/FFTW.v3.3.9.x86_64-linux-gnu.tar.gz"
[[FFTW]]
arch = "powerpc64le"
git-tree-sha1 = "8dcc8fe63792b241d1a9e00640f0498d75173b85"
libc = "glibc"
os = "linux"

    [[FFTW.download]]
    sha256 = "d289d32fd9142abb4d59f8fb00348ae6073f476b497ee1ab50744d0ec78b3d81"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+4/FFTW.v3.3.9.powerpc64le-linux-gnu.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "686f343230e1853cc948cd0736b57067c66bca4b"
os = "macos"

    [[FFTW.download]]
    sha256 = "e71fc4d67116902e693dc5ee6082866c397fa68e86b03c32842a8662c534f422"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+4/FFTW.v3.3.9.x86_64-apple-darwin14.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "cf5c43ebb12a528e09f8c0248749b8113abf6c94"
os = "freebsd"

    [[FFTW.download]]
    sha256 = "601fc8a95783753ec25ff53acc2accb5e6b4ef4d6013715c57acc0a70c065509"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+4/FFTW.v3.3.9.x86_64-unknown-freebsd11.1.tar.gz"
[[FFTW]]
arch = "i686"
git-tree-sha1 = "bb9ca6ed8ac179209aced975544da08a9907e1b0"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "a1ee1fbe0d532fe84b7ca3d06be08667e1d4574d9903a860d1f8914c689eb4f5"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+4/FFTW.v3.3.9.i686-linux-musl.tar.gz"
[[FFTW]]
arch = "armv7l"
git-tree-sha1 = "e8c98ad9fcf35c8fc28729e73d99812ab3a1b45c"
libc = "musl"
os = "linux"

    [[FFTW.download]]
    sha256 = "51d01674141148df01420aa1ed11151031e5a10dedf8ce6808df09d02296d9ea"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+4/FFTW.v3.3.9.armv7l-linux-musleabihf.tar.gz"
[[FFTW]]
arch = "x86_64"
git-tree-sha1 = "44442ba57c9fa8cb5ad19badb135de445617dae7"
os = "windows"

    [[FFTW.download]]
    sha256 = "ea82f97e3f77bdd9a5f85ba8d5275d2024d0384e1b09adc3e2d5696a53cc3937"
    url = "https://github.com/JuliaBinaryWrappers/FFTW_jll.jl/releases/download/FFTW-v3.3.9+4/FFTW.v3.3.9.x86_64-w64-mingw32.tar.gz"
